# You must change these to your own details.
[package]
name = "tari_wallet_lib"
version = "0.1.0"
categories = ["wasm"]
readme = "README.md"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = "z"
strip = true
lto = true
codegen-units = 1

[dependencies]
wasm-bindgen = "0.2"
serde-wasm-bindgen = "0.6.0"
console_error_panic_hook = "0.1"
tari_crypto = { version = "0.17" }
thiserror = "1.0.49"
tari_template_lib = { git="https://github.com/tari-project/tari-dan.git" }
tari_template_abi = { git="https://github.com/tari-project/tari-dan.git" }
digest = "0.9.0"
serde = "1.0.126"
serde_json = "1.0"
base64 = "0.21.0"
rand = { version = "0.7.3", features = ["wasm-bindgen"] }

# These crates are used for running unit tests.
[dev-dependencies]
wasm-bindgen-test = "0.3.37"
